name: Upload to Nuget

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Clear Releases
        run: rm -rf Grecs/bin/*
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release Grecs
      - name: Create the package
        run: dotnet pack --configuration Release Grecs
      - name: Publish the package to Nuget
        run: dotnet nuget push Grecs/bin/Release/*.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json
