name: Upload to Nuget

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # SDK Version to use.
      - run: dotnet build --configuration Release Grecs
      - name: Create the package
        run: dotnet pack --configuration Release Grecs
      - name: Publish the package to Nuget
        run: dotnet nuget push Grecs/bin/Release/*.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate -n
